---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: user-service-secrets
  namespace: ecommerce
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "pip-project-ecommerce-db-credentials"
        objectType: "secretsmanager"
        jmesPath:
          - path: username
            objectAlias: db_username
          - path: password
            objectAlias: db_password
          - path: host
            objectAlias: db_host
          - path: port
            objectAlias: db_port
      - objectName: "/pip-project-ecommerce/prod/app/jwt-secret"
        objectType: "ssmparameter"
        objectAlias: jwt_secret
      - objectName: "/pip-project-ecommerce/prod/app/internal-service-key"
        objectType: "ssmparameter"
        objectAlias: internal_service_key
  secretObjects:
  - secretName: user-db-url
    type: Opaque
    data:
    - objectName: db_host
      key: host
    - objectName: db_username
      key: username
    - objectName: db_password
      key: password
  - secretName: app-secrets
    type: Opaque
    data:
    - objectName: jwt_secret
      key: jwt_secret
    - objectName: internal_service_key
      key: internal_service_key
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: product-service-secrets
  namespace: ecommerce
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "pip-project-ecommerce-db-credentials"
        objectType: "secretsmanager"
        jmesPath:
          - path: username
            objectAlias: db_username
          - path: password
            objectAlias: db_password
          - path: host
            objectAlias: db_host
  secretObjects:
  - secretName: product-db-url
    type: Opaque
    data:
    - objectName: db_host
      key: host
    - objectName: db_username
      key: username
    - objectName: db_password
      key: password
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: cart-service-secrets
  namespace: ecommerce
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "pip-project-ecommerce-db-credentials"
        objectType: "secretsmanager"
        jmesPath:
          - path: username
            objectAlias: db_username
          - path: password
            objectAlias: db_password
          - path: host
            objectAlias: db_host
      - objectName: "pip-project-ecommerce/prod/redis/auth-token"
        objectType: "secretsmanager"
        jmesPath:
          - path: auth_token
            objectAlias: redis_auth_token
  secretObjects:
  - secretName: cart-db-url
    type: Opaque
    data:
    - objectName: db_host
      key: host
    - objectName: db_username
      key: username
    - objectName: db_password
      key: password
  - secretName: redis-secrets
    type: Opaque
    data:
    - objectName: redis_auth_token
      key: auth_token
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: order-service-secrets
  namespace: ecommerce
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "pip-project-ecommerce-db-credentials"
        objectType: "secretsmanager"
        jmesPath:
          - path: username
            objectAlias: db_username
          - path: password
            objectAlias: db_password
          - path: host
            objectAlias: db_host
  secretObjects:
  - secretName: order-db-url
    type: Opaque
    data:
    - objectName: db_host
      key: host
    - objectName: db_username
      key: username
    - objectName: db_password
      key: password
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: payment-service-secrets
  namespace: ecommerce
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "pip-project-ecommerce-db-credentials"
        objectType: "secretsmanager"
        jmesPath:
          - path: username
            objectAlias: db_username
          - path: password
            objectAlias: db_password
          - path: host
            objectAlias: db_host
      - objectName: "pip-project-ecommerce/prod/redis/auth-token"
        objectType: "secretsmanager"
        jmesPath:
          - path: auth_token
            objectAlias: redis_auth_token
  secretObjects:
  - secretName: payment-db-url
    type: Opaque
    data:
    - objectName: db_host
      key: host
    - objectName: db_username
      key: username
    - objectName: db_password
      key: password
  - secretName: redis-secrets
    type: Opaque
    data:
    - objectName: redis_auth_token
      key: auth_token
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: notification-service-secrets
  namespace: ecommerce
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "/pip-project-ecommerce/prod/app/jwt-secret"
        objectType: "ssmparameter"
        objectAlias: jwt_secret
  secretObjects:
  - secretName: notification-app-secrets
    type: Opaque
    data:
    - objectName: jwt_secret
      key: jwt_secret
