import 'dotenv/config';import express from 'express';import cors from 'cors';import helmet from 'helmet';import jwt from 'jsonwebtoken';import {PrismaClient} from '@prisma/client';import {SNSClient,PublishCommand} from '@aws-sdk/client-sns';
const app=express(),prisma=new PrismaClient(),port=Number(process.env.PORT||4004),secret=process.env.JWT_SECRET||'dev-secret',paymentUrl=process.env.PAYMENT_SERVICE_URL||'http://localhost:4005',userUrl=process.env.USER_SERVICE_URL||'http://localhost:4001',internalKey=process.env.INTERNAL_SERVICE_KEY||'dev-internal-key',sns=new SNSClient({region:process.env.AWS_REGION||'ap-south-1'});app.use(helmet());app.use(cors());app.use(express.json());
function auth(req:any,res:any,next:any){try{const h=req.headers.authorization;if(!h?.startsWith('Bearer '))return res.status(401).json({message:'Unauthorized'});req.user=jwt.verify(h.slice(7),secret);next()}catch{return res.status(401).json({message:'Invalid token'})}}
async function notify(e:any){if(process.env.SNS_TOPIC_ARN)await sns.send(new PublishCommand({TopicArn:process.env.SNS_TOPIC_ARN,Message:JSON.stringify(e)}))}
app.get('/health',(_,r)=>r.json({service:'order-service',status:'ok'}));
app.post('/api/orders',auth,async(req:any,res)=>{const {paymentTransactionId,totalAmount,address,items}=req.body;if(!paymentTransactionId||!totalAmount||!address||!Array.isArray(items)||!items.length)return res.status(400).json({message:'paymentTransactionId, totalAmount, address and items are required'});const ph=req.headers.authorization;const vr=await fetch(`${paymentUrl}/api/payments/${encodeURIComponent(paymentTransactionId)}`,{headers:{Authorization:String(ph||'')}});if(!vr.ok)return res.status(400).json({message:'Payment could not be verified'});const vd=await vr.json();if(vd.payment?.status!=='SUCCESS')return res.status(400).json({message:'Payment is not successful'});if(Number(vd.payment.amount)!==Number(totalAmount))return res.status(400).json({message:'Payment amount mismatch'});const order=await prisma.order.create({data:{userId:req.user.sub,paymentTransactionId,totalAmount,addressJson:address,items:{create:items.map((i:any)=>({productId:i.productId,productName:i.productName||'Product',quantity:Number(i.quantity),unitPrice:i.unitPrice}))}},include:{items:true}});let contact:any={};try{const ur=await fetch(`${userUrl}/internal/users/${req.user.sub}`,{headers:{'x-internal-key':internalKey}});if(ur.ok)contact=(await ur.json()).user||{}}catch{} await notify({type:'ORDER_CONFIRMED',userId:req.user.sub,name:contact.name,email:contact.email,phone:contact.phone,orderId:order.id,totalAmount:Number(order.totalAmount)});res.status(201).json({order})});
app.get('/api/orders',auth,async(req:any,res)=>{const orders=await prisma.order.findMany({where:{userId:req.user.sub},include:{items:true},orderBy:{createdAt:'desc'}});res.json({orders})});
app.get('/api/orders/:id',auth,async(req:any,res)=>{const o=await prisma.order.findFirst({where:{id:req.params.id,userId:req.user.sub},include:{items:true}});return o?res.json({order:o}):res.status(404).json({message:'Order not found'})});
app.patch('/api/orders/:id/delivery-status',async(req,res)=>{const allowed=['PROCESSING','PACKED','SHIPPED','OUT_FOR_DELIVERY','DELIVERED','CANCELLED'];if(!allowed.includes(req.body.deliveryStatus))return res.status(400).json({message:'Invalid delivery status'});const o=await prisma.order.update({where:{id:req.params.id},data:{deliveryStatus:req.body.deliveryStatus}});res.json({order:o})});
app.listen(port,()=>console.log(`order-service listening on ${port}`));
