apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: ecommerce
  labels:
    app: product-service
spec:
  type: ClusterIP
  selector:
    app: product-service
    tier: backend
  ports:
  - name: http
    port: 4002        # FIXED: was 3002
    targetPort: 4002
    protocol: TCP
