import 'dotenv/config'; import express from 'express'; import cors from 'cors'; import helmet from 'helmet';
import { PrismaClient } from '@prisma/client'; import bcrypt from 'bcryptjs'; import jwt from 'jsonwebtoken'; import { SNSClient, PublishCommand } from '@aws-sdk/client-sns';
const app=express(), prisma=new PrismaClient(), port=Number(process.env.PORT||4001), secret=process.env.JWT_SECRET||'dev-secret', internalKey=process.env.INTERNAL_SERVICE_KEY||'dev-internal-key';
app.use(helmet()); app.use(cors()); app.use(express.json());
const sns=new SNSClient({region:process.env.AWS_REGION||'ap-south-1'});
async function notify(event:any){if(!process.env.SNS_TOPIC_ARN)return; await sns.send(new PublishCommand({TopicArn:process.env.SNS_TOPIC_ARN,Message:JSON.stringify(event)}));}
function token(u:{id:string,email:string}){return jwt.sign({sub:u.id,email:u.email},secret,{expiresIn:'1h'});}
app.get('/health',(_,r)=>r.json({service:'user-service',status:'ok'}));
app.post('/api/users/register',async(req,res)=>{try{const {name,email,phone,password}=req.body;if(!name||!email||!phone||!password)return res.status(400).json({message:'name, email, phone and password are required'});const exists=await prisma.user.findFirst({where:{OR:[{email},{phone}]}});if(exists)return res.status(409).json({message:'Email or phone already registered'});const passwordHash=await bcrypt.hash(password,12);const u=await prisma.user.create({data:{name,email,phone,passwordHash}});return res.status(201).json({user:{id:u.id,name:u.name,email:u.email,phone:u.phone}})}catch(e){return res.status(500).json({message:'Registration failed'})}});
app.post('/api/users/login',async(req,res)=>{try{const {email,phone,password}=req.body;if(!email||!phone||!password)return res.status(400).json({message:'email, phone and password are required'});const u=await prisma.user.findUnique({where:{email}});if(!u||u.phone!==phone||!(await bcrypt.compare(password,u.passwordHash)))return res.status(401).json({message:'Invalid credentials'});const t=token(u);await notify({type:'USER_LOGIN_SUCCESS',userId:u.id,name:u.name,email:u.email,phone:u.phone});return res.json({token:t,user:{id:u.id,name:u.name,email:u.email,phone:u.phone}})}catch(e){return res.status(500).json({message:'Login failed'})}});
function auth(req:any,res:any,next:any){try{const h=req.headers.authorization;if(!h?.startsWith('Bearer '))return res.status(401).json({message:'Unauthorized'});req.user=jwt.verify(h.slice(7),secret);next()}catch{return res.status(401).json({message:'Invalid or expired token'})}}
app.get('/internal/users/:id',async(req,res)=>{if(req.headers['x-internal-key']!==internalKey)return res.status(403).json({message:'Forbidden'});const u=await prisma.user.findUnique({where:{id:req.params.id},select:{id:true,name:true,email:true,phone:true}});return u?res.json({user:u}):res.status(404).json({message:'User not found'})});
app.get('/api/users/me',auth,async(req:any,res)=>{const u=await prisma.user.findUnique({where:{id:req.user.sub},select:{id:true,name:true,email:true,phone:true,createdAt:true}});return u?res.json({user:u}):res.status(404).json({message:'User not found'})});
app.patch('/api/users/me',auth,async(req:any,res)=>{const {name,email,phone}=req.body;const u=await prisma.user.update({where:{id:req.user.sub},data:{...(name&&{name}),...(email&&{email}),...(phone&&{phone})},select:{id:true,name:true,email:true,phone:true}});res.json({user:u})});
app.listen(port,()=>console.log(`user-service listening on ${port}`));
