apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: ecommerce
type: Opaque
stringData:
  username: postgres
  password: "changeme123!"  # CHANGE THIS IN PRODUCTION
---
apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: ecommerce
type: Opaque
stringData:
  host: postgres-service.ecommerce.svc.cluster.local
  username: postgres
  password: "changeme123!"  # CHANGE THIS IN PRODUCTION
