apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: ecommerce
  labels:
    app: postgres
spec:
  type: ClusterIP
  selector:
    app: postgres
    tier: database
  ports:
  - name: postgres
    port: 5432
    targetPort: 5432
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-headless
  namespace: ecommerce
  labels:
    app: postgres
spec:
  clusterIP: None
  selector:
    app: postgres
    tier: database
  ports:
  - name: postgres
    port: 5432
    targetPort: 5432
    protocol: TCP
