apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: ecommerce
  labels:
    app: payment-service
spec:
  type: ClusterIP
  selector:
    app: payment-service
    tier: backend
  ports:
  - name: http
    port: 4005        # FIXED: was 3005
    targetPort: 4005
    protocol: TCP
